- name: We install mongodb component
  hosts: mongodb
  become: yes
  tasks: 
  - name:  copy mongodb.repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name:  Install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
  - name: mongodb starting service
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started
  - name: Replace old hostname with new hostname
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: mongodb enable and restart
    ansible.builtin.service:
      name: mongod
      state: restarted
