- name: Install and Configure Redis on EC2 (Amazon Linux / CentOS 8 / RHEL 8)
  hosts: redis
  become: yes
  tasks:

    - name: Get OS Information
      ansible.builtin.shell: "cat /etc/os-release"
      register: os_info
      changed_when: false

    - name: Set OS family variable
      ansible.builtin.set_fact:
        os_family: >-
          {% if 'Amazon Linux' in os_info.stdout %}amazon
          {% elif 'CentOS' in os_info.stdout or 'Red Hat' in os_info.stdout %}rhel
          {% else %}unknown{% endif %}

    - name: Debug OS Family
      ansible.builtin.debug:
        msg: "Detected OS: {{ os_family }}"

    - name: Install Redis on Amazon Linux
      when: os_family == "amazon"
      block:
        - name: Enable Amazon Linux Extras for Redis
          ansible.builtin.command: amazon-linux-extras enable redis6
          changed_when: false

        - name: Install Redis on Amazon Linux
          ansible.builtin.yum:
            name: redis
            state: present

    - name: Install Redis on RHEL/CentOS 8
      when: os_family == "rhel"
      block:
        - name: Install Redis repo
          ansible.builtin.yum:
            name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
            state: present
            disable_gpg_check: true

        - name: Enable Redis 6.2 module
          ansible.builtin.shell: yum module enable redis:remi-6.2 -y
          args:
            warn: false

        - name: Install Redis on RHEL/CentOS
          ansible.builtin.yum:
            name: redis
            state: present

    - name: Find Redis Configuration File
      ansible.builtin.find:
        paths:
          - /etc/redis
          - /etc
        patterns: "redis.conf"
        use_regex: false
      register: redis_conf_file

    - name: Debug Found Redis Config File
      ansible.builtin.debug:
        msg: "Redis config file found at: {{ redis_conf_file.files[0].path if redis_conf_file.matched > 0 else 'NOT FOUND' }}"

    - name: Allow remote connections to Redis
      ansible.builtin.replace:
        path: "{{ redis_conf_file.files[0].path }}"
        regexp: '^bind 127\.0\.0\.1'
        replace: 'bind 0.0.0.0'
      when: redis_conf_file.matched > 0

    - name: Start and enable Redis service on Amazon Linux
      when: os_family == "amazon"
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes

    - name: Start and enable Redis service on RHEL/CentOS
      when: os_family == "rhel"
      ansible.builtin.systemd:
        name: redis-server
        state: started
        enabled: yes
