- name: Install and Configure Redis on EC2 (CentOS 8/RHEL 8)
  hosts: redis
  become: yes
  tasks:

    - name: Get OS Version
      ansible.builtin.shell: "rpm -q --queryformat '%{VERSION}' redhat-release || rpm -q --queryformat '%{VERSION}' centos-release"
      register: os_version
      changed_when: false

    - name: Install Redis repo (Compatible with RHEL 8.x)
      ansible.builtin.shell: |
        if [[ "{{ os_version.stdout }}" == "8.9" ]]; then
          yum install -y https://rpms.remirepo.net/enterprise/remi-release-8.9.rpm
        else
          yum install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        fi
      args:
        warn: false

    - name: Clean yum metadata cache
      ansible.builtin.command: yum clean all
      changed_when: false

    - name: Enable Redis 6.2 module
      ansible.builtin.shell: yum module enable redis:remi-6.2 -y
      args:
        warn: false  # Suppress warnings

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Allow remote connections to Redis
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '^bind 127\.0\.0\.1'
        replace: 'bind 0.0.0.0'
      with_first_found:
        - /etc/redis/redis.conf
        - /etc/redis.conf

    - name: Reload systemd to recognize Redis service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Redis service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
