- name: Install Shipping component
  hosts: shipping
  become: yes
  tasks:
    - name: Install Maven
      ansible.builtin.yum:
        name: maven
        state: installed

    - name: Check if roboshop user exists
      ansible.builtin.command: id roboshop
      register: out
      ignore_errors: true

    - name: Create roboshop user if not exists
      when: out.rc != 0
      ansible.builtin.user:
        name: roboshop

    - name: Ensure /app and /app/schema directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /app
        - /app/schema

    - name: Download and extract shipping service
      ansible.builtin.unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
        dest: /app
        remote_src: yes

    - name: Copy shipping.sql to /app/schema/
      ansible.builtin.copy:
        src: shipping.sql  # This file MUST be present in the Ansible Controller
        dest: /app/schema/shipping.sql
        mode: '0644'

    - name: Maven package
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: Rename jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: Copy shipping service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
    
    - name: Restart shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: true

    - name: Install MySQL client
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: Load MySQL schema
      ansible.builtin.shell: |
        mysql -h mysql.munidevops.shop -uroot -pRoboShop@1 < /app/schema/shipping.sql
      args:
        executable: /bin/bash

    - name: Restart shipping service
      ansible.builtin.service:
        name: shipping
        state: restarted
        enabled: true